### ISSUE TITLE
Jetpack added via Attachment Plate can't be disabled.

### ISSUE THREAD

**Issue by StubornOne** [Su5eD/IC2-Patcher#17]

**Comment by Kanzaji** [comment]
Hey There!
I'm fairly sure this is something I can't fix, as in stock IC2, Nanosuit doesn't have a jetpack. If it has in your case, it's probably from an addon or some compatibility mod?

I'm going to close this for now, but if you meant a jetpack from a QuantumSuit, feel free to open it back up with clarification and more information (Like your IC2 / IC2-Patcher version, etc) 😄

**Comment by StubornOne** [comment]
Ok, so I can make nanosuit without jetpack but then add it in crafting table. IC2 version is 2.8.222-ex112 and Patcher is 2.0.7
