### ISSUE TITLE
IC2 Patcher break Chunk Loader

### ISSUE THREAD

**Issue by Krutoy242** [Su5eD/IC2-Patcher#18]
- industrialcraft-2-2.8.222-ex112
- ic2patcher-2.0.7

Chunk Loader cant load chunks. No 0:0 chunk selected and unable to select new chunks in GUI.

### https://mclo.gs/Yk2KP1G

![image](https://github.com/Su5eD/IC2-Patcher/assets/936618/fe3974c0-9726-4df4-962a-6c99ae3e0ab2)

This issue does not happen on `ic2patcher-2.0.3`

**Comment by Kanzaji** [comment]
Thanks for the report! I will try to investigate the issue whenever I can, however I don't have much time recently so it might take a bit >.>

**Comment by Errelian** [comment]
Did some testing in singleplayer, the chunk loader in 2.0.5 works, in 2.0.6 it no longer does. It seems like 2.0.6 introduced the issue.

**Comment by Kanzaji** [comment]
> Did some testing in singleplayer, the chunk loader in 2.0.5 works, in 2.0.6 it no longer does. It seems like 2.0.6 introduced the issue.

This... might be hard to track down then.
https://github.com/Su5eD/IC2-Patcher/commit/8c6f7f1bbef0a3b28212efcba2082892df64cb52 (This is big release in comparison to the entire project)

**Comment by Kanzaji** [comment]
> > Did some testing in singleplayer, the chunk loader in 2.0.5 works, in 2.0.6 it no longer does. It seems like 2.0.6 introduced the issue.
> 
> This... might be hard to track down then >.>
> https://github.com/Su5eD/IC2-Patcher/commit/8c6f7f1bbef0a3b28212efcba2082892df64cb52 (This is big release in comparison to the entire project)
> 
> I have my suspect, however I would need to confirm if that is the case. If so, I will already have 2 issues that are caused by the same thing. If that's the case... now just need to find the source ^^"

I was indeed correct. This issue and #21 were caused by incorrect decoding of collection objects received from the server.

**Comment by Krutoy242** [comment]
This issue is still actual! If i can somehow test it to be released faster - please let me know.
