### ISSUE TITLE
OD & OV Scanner crashes

### ISSUE THREAD

**Issue by Frogger60** [Su5eD/IC2-Patcher#21]
Using an OD Scanner or OV Scanner causes the game to crash. When playing multiplayer, it crashes Minecraft back to Launcher, in Singleplayer, it crashes back to main menu.

Step 1: Use an OD Scanner or OV Scanner
Step 2: Crash

I have tested both with the Patcher and without on the same world. Only crashes with the Patcher.

[latest.log](https://github.com/Su5eD/IC2-Patcher/files/15335980/latest.log)

[crash-2024-05-16_15.36.15-client.txt](https://github.com/Su5eD/IC2-Patcher/files/15335989/crash-2024-05-16_15.36.15-client.txt)

**Comment by Kanzaji** [comment]
Hey there, thanks for the report!

I investigated it a little already, trying to narrow down the part of the code where it might be broken.
The issue is that I narrowed it down to the base patches (Patches that make the Decompiled IC2 possible to recompile) so... fixing this might take some time >.>

**Comment by xJon** [comment]
@Kanzaji Any chance for a new build with the fixes? 👀

**Comment by Kanzaji** [comment]
You are lucky, as I'm starting my vacation tomorrow so I will get to it asap, and the build should *hopefully* be around this time tomorrow 😄
Didn't had time at all to just port the changes to other supported IC2 versions.

**Comment by xJon** [comment]
@Kanzaji Still no new build on CurseForge unfortunately...

**Comment by Kanzaji** [comment]
> @Kanzaji Still no new build on CurseForge unfortunately...

Waiting for the reply from the Owner (@Su5eD ) about the changes made ^^" Whenever I get it I will upload the new version to CF as fast as possible >.>
