### ISSUE TITLE
Crash on startup w/ Classic profile (fixUraniumCellRecipe)

### ISSUE THREAD

**Issue by nan0bug00** [Su5eD/IC2-Patcher#24]
**Describe the bug**
After changing the profile from `Experimental` to `Classic` in `ic2.ini`, Minecraft crashes on loading.  Excerpt of crash log:

```
Time: 2024-09-26 06:19:10 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from IC2 Patcher (ic2patcher)
Caused by: java.lang.NoSuchMethodError: net.minecraft.inventory.InventoryCrafting.setInventorySlotContents(ILnet/minecraft/item/ItemStack;)V
    at mods.su5ed.ic2patcher.util.RecipeUtil.getCraftingRecipe(RecipeUtil.java:15)
    at mods.su5ed.ic2patcher.Patcher.fixUraniumCellRecipe(Patcher.java:48)
    at mods.su5ed.ic2patcher.Patcher.preInit(Patcher.java:32)
```

Full log available [here.](https://mclo.gs/Txozchy)  (Note:  I was able to reproduce this in a separate instance with only IC2 + IC2 Patcher, so it's not related to other mods.)

**To Reproduce**
1. Set up a modpack instance with IndustrialCraft 2 (I'm using 2.8.222-ex112) and IC2 Patcher 2.0.8.  
2. Launch to generate ic2.ini in config folder.  Close game.
3. Open `config/ic2.ini` in a text editor and change line 165 from `selected = Experimental` to `selected = Classic`
4. Try to launch the game again.
5. See error

**Expected behavior**
The game should launch.

**Comment by Kanzaji** [comment]
Thanks for the report! I will try to fix the issue in my free time 😅

**Comment by EndangeredNayla** [comment]
I already reported this bug to Su5eD not realizing there was another maintainer. 2.0.3 of the mod works fine. If you want to backtrack the issue from there.

**Comment by Kanzaji** [comment]
When you find a bit of time, decide to work with IC2... and IC2 Maven has to be broken >.>
![obraz](https://github.com/user-attachments/assets/e8cdbce1-5bf8-4e07-a5b6-d76e70840330)

**Comment by Kanzaji** [comment]
So, it appears the issue is "Bad Compiler RNG" - Pretty much was unlucky enough for NG to not obfuscate everything for some reason >.> I will push out a fix tomorrow with a working build 😄

**Comment by Kanzaji** [comment]
New release with this issue fixed is out on CF 😄

**Comment by nan0bug00** [comment]
Thank you!

**Comment by Kanzaji** [comment]
Currently the latest version of IC2-Patcher again has this issue 😓 
I finally fixed the Release Jar task however, so the next release will work on Classic mode again 😅
