### ISSUE TITLE
[Patch Request] IC2 Cable bug

### ISSUE THREAD

**Issue by Irgendwer01** [Su5eD/IC2-Patcher#4]
**Link to the bug IC2's issue tracker**
https://bt.industrial-craft.net/view.php?id=1959
https://forum.industrial-craft.net/thread/16379-ic2-enet-bug-1-12/

**Describe the bug**
Sometime when switching Dimensions and then going back to the Dimension where the cables are, all Cables in the Dimensions will be instantly disconnected.

**To Reproduce**
1. Place IC2 cables with Machines
2. Go to the nether
3. Go back
4. see issue.

**Expected behavior**
That they not Disconnect.

**Comment by Su5eD** [comment]
Have you been able to reproduce this bug? It seems to occur really rarely

**Comment by Irgendwer01** [comment]
> Have you been able to reproduce this bug? It seems to occur really rarely

@Su5eD Yes, its very annoying to get away since we don't really know what exactly triggers the bug, something in world loading and unloading is causing it, it makes that many players need redo all setup they done only to avoid the bug.
