### ISSUE TITLE
Ejector upgrade does not eject to AE2 ME Interfaces

### ISSUE THREAD

**Issue by TheNumenorean** [Su5eD/IC2-Patcher#7]
**Describe the bug**
The Ejector upgrade does not eject to AE2 ME Interfaces, which should be possible (since ME interfaces can take items and act as inventories) and works correctly in IC2Classic.

**To Reproduce**
1. Setup a macerator with an ME interface on top
2. Right click the top of a block with an ejector upgrade to have it eject to the top of the machine.
3. Put the ejector upgrade in the macerator.
4. Add some coal to macerate.
5. Notice that the coal dust remains in the machine after being created.

**Expected behavior**
Generated items get sent to an adjacent ME interface and are absorbed into the ME system.

**Additional context**
![image](https://user-images.githubusercontent.com/809047/159137255-859b4829-779c-4914-88c4-b4fa8f20ea07.png)
![image](https://user-images.githubusercontent.com/809047/159137265-f8febdb9-71f7-4d56-9cc2-6442909d6a79.png)

**Comment by TheNumenorean** [comment]
https://bt.industrial-craft.net/view.php?id=2551

**Comment by Kanzaji** [comment]
Very old patch request, however I will work on this in a free time in the near future :D
Just as a note, it seems only the Panel ME Interface has this issue, Normal ME Interface works as expected.
